### ISSUE TITLE
pandoc tries to convert the favicon

### ISSUE THREAD

**Issue by Mik3Rizzo** [Linbreux/wikmd#28]
I noticed that two `GET` requests are made once a wiki page has been opened:
- page request
- favicon request

Adding a bit of logging details, this is the console out:
```
[2022-03-14 15:20:35,028] INFO in wiki: Converting wiki\How to use the wiki.md to HTML with pandoc
[2022-03-14 15:20:35,798] INFO in wiki: Showing html page of How to use the wiki
[2022-03-14 15:20:36,408] INFO in wiki: Converting wiki\favicon.ico.md to HTML with pandoc
[2022-03-14 15:20:36,409] INFO in wiki: source_file is not a valid path
```
Pandoc tries to convert to HTML both the page (that is correct) and the favicon (that is not desirable).
I'll try to fix that.

**Comment by Linbreux** [comment]
Hi I think thats because you have a markdown file in the wiki folder '''favicon.ico.md'''

All markdown files will be rendered to html.

Make sure you put your commits for different topics and features on different branches 😉

[https://dev.to/projectpage/how-to-move-a-commit-to-another-branch-in-git-4lj4](https://dev.to/projectpage/how-to-move-a-commit-to-another-branch-in-git-4lj4)

**Comment by Mik3Rizzo** [comment]
> you have a markdown file in the wiki folder '''favicon.ico.md'''

Uhm, I don't have such a file...

> Make sure you put your commits for different topics and features on different branches 😉

I swear I'll learn to manage branches for the next time, up to now I've developed all in the main branch... thank you for the suggested guide!

Anyway, I fixed this favicon bug with a simple check.
