### ISSUE TITLE
Redirect all .md files to wikimd?

### ISSUE THREAD

**Issue by SmartBoy84** [Linbreux/wikmd#83]
For me, the ideal setup would be one where I am able to have all my markdown files rendered and displayed by wikimd on the "main" domain and on a subdomain (or `/edit`) the same URL would allow the file to be edited?
So for example, at `domain.com/file.md` I'd be able to just view the file as if it were a normal page then at `edit.domain.com/file.md` I'd be able to sign and edit the file.

Currently, I use Nginx to forward all URLs ending with `.md` to a simple js markdown "processor" that I wrote that renders and displays the file. For now, I edit these files through SSH + nano 😔
Would it possible to forward all .md files to wikimd to display even if they aren't ones that are in the scope of wikimd?

Further, would it be possible to hide the header for wikimd?

**Comment by Linbreux** [comment]
Hi @SmartBoy84 

It is possible to password protect editing on the wiki, it's documented in the  [docs](https://linbreux.github.io/wikmd/environment%20variables.html#password-protect), if that's why you would like to use a subdomain. Otherwise I would suggest you to run two instances, one with edit rights and another one with password protection. 

You can use a [custom data path](https://linbreux.github.io/wikmd/environment%20variables.html#custom-data-path) to specify a specific folder on your system that's not in the wikmd folder.

You can change the `base.html`file and remove the header if you want.

Hope this helps! Let me know if something wasn't clear!

**Comment by Linbreux** [comment]
You want every markdown file on your system to be shown in the wiki?

Change in `wikmd-config.yaml`the `wiki_directory: "wiki"`variable to `wiki_directory: "/"`or `wiki_directory: "/home/username"`
